apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftwrapped-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giftwrapped-mongo
  template:
    metadata:
      labels:
        app: giftwrapped-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: giftwrapped-mongo
spec:
  selector:
    app: giftwrapped-mongo
  ports:
    - port: 27017
      targetPort: 27017
